blog_sys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from my_blog import views
from blog_sys import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 登录页面
    url(r'^login/', views.my_login, name='login'),

    # 注册页面
    url(r'^register/', views.register, name='register'),

    # 主页面
    url(r'^index/$', views.index, name='index'),
    url(r'^$', views.index, name='index'),

    # 功能
    url(r'^logout/', views.my_logout, name='logout'),
    url(r'^captcha/', views.get_valid_img, name='get_valid_img'),
    url(r'^reset_pwd/', views.reset_pwd, name='reset_pwd'),
    url(r'fans_for/', views.fans_for, name='fans_for'),

    # 文章详情页面

    url(r'^blog/', include('my_blog.urls')),
]

urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

my_blog/urls.py
# -*- coding: utf-8 -*-   @Time    : 18-1-25 下午6:58
# @Author  : QiHanFang    @Email   : qihanfang@foxmail.com
from django.conf.urls import url
from my_blog import views


urlpatterns = [
    # 方式1、常规评论，在子评论上方追加父评论内容
    # url(r'^p/(\d{1,5})/', views.article_detail, name='article'),

    # 方式2、利用树形结构评论的文章详情页
    # url(r'^p/(\d{1,5})/', views.article_detail_2, name='article'),

    # 方式3、运用自定义标签在前端渲染评论
    url(r'^p/(\d{1,5})/', views.article_detail_page, name='article'),

    url(r'^favor/', views.user_favor, name='user_favor'),
    url(r'^comment/favor/', views.comment_favor, name='comment_favor'),
    url(r'^comment/', views.user_comment, name='user_comment'),

    # 注意必须放在最后,全能匹配

    # 个人主页/文章分类/标签分类
    # url(r'^(\S+)/$', views.user_page, name='user_page'),
    url(r'^(?P<site>.*)/home/$', views.user_page, name='user_site'),

]

my_blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.BigAutoField(primary_key=True)
    nickname = models.CharField(max_length=50, verbose_name='昵称', null=True, blank=True)
    telephone = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    avatar = models.FileField(verbose_name='头像',upload_to='user/%Y/%m')
    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        db_table='用户信息'


class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(UserInfo, verbose_name='博主', related_name='users')
    follower = models.ForeignKey(UserInfo, verbose_name='粉丝', related_name='followers')

    class Meta:
        verbose_name='用户粉丝'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.follower.username+' 关注了 '+self.user.username


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo', to_field='nid')

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name
        db_table='博客设置信息'

    def __str__(self):
        return self.title


class SiteCate(models.Model):
    title = models.CharField(max_length=32, verbose_name='网站分类')

    class Meta:
        verbose_name = '网站分类'
        verbose_name_plural = verbose_name
        db_table='网站文章分类'

    def __str__(self):
        return self.title



class SiteCateDetail(models.Model):
    title = models.CharField(max_length=32, verbose_name='网站详细分类')
    parent = models.ForeignKey(SiteCate)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '网站分类详情'
        verbose_name_plural = verbose_name
        db_table='网站详细分类'



class Category(models.Model):
    """博主个人文章分类表"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '自定义分类'
        verbose_name_plural = verbose_name
        ordering = ['title']
        db_table='自定义分类'


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    comment_num= models.IntegerField(default=0)
    poll_num= models.IntegerField(default=0)
    category = models.ForeignKey(verbose_name='自定义文章类型', to='Category', to_field='nid', null=True)
    read_num = models.IntegerField(verbose_name='阅读数', default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')
    site_cate = models.ForeignKey(SiteCateDetail, verbose_name='网站分类', null=True, blank=True)
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        db_table='文章'


class ArticleDetail(models.Model):
    """文章详细表"""
    content = models.TextField(verbose_name='文章内容', )
    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')

    class Meta:
        verbose_name = '文章详情'
        verbose_name_plural = verbose_name
        db_table='文章详情'

    def __str__(self):
        return self.article.title


class Comment(models.Model):
    """    评论表"""
    nid = models.BigAutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_id = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    poll_num = models.IntegerField(default=0)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        db_table='用户评论'


class Poll(models.Model):
    """文章点赞表"""
    user = models.ForeignKey('UserInfo', null=True, verbose_name='评论者')
    article = models.ForeignKey("Article", null=True, verbose_name='文章')

    class Meta:
        verbose_name = '文章点赞'
        verbose_name_plural = verbose_name
        unique_together = ['user', 'article']
        db_table='用户点赞'

    def __str__(self):
        return self.article.title


class Comment_poll(models.Model):
    """评论点赞表"""
    poll_user = models.ForeignKey('UserInfo', verbose_name='评论点赞者')
    comment = models.ForeignKey("Comment", verbose_name='评论')

    class Meta:
        verbose_name = '评论点赞'
        verbose_name_plural = verbose_name
        unique_together = ['poll_user', 'comment']

    def __str__(self):
        return self.poll_user.username + '认同了' + str(self.comment.nid)


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.title+'------   '+self.blog.user.username


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        verbose_name= '文章标签关系表'
        verbose_name_plural = verbose_name
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        return '文章'+str(self.article.nid) + ' 绑定标签 ' + self.tag.title

my_blog/forms.py
# -*- coding: utf-8 -*-   @Time    : 18-1-25 下午6:58
# @Author  : QiHanFang    @Email   : qihanfang@foxmail.com

from django import forms
from django.forms import widgets
from django.forms import ValidationError


class RegisterForm(forms.Form):
    username = forms.CharField(min_length=2, widget=widgets.TextInput(attrs={"placeholder": "用户名", "class": "form-control"}))
    password1 = forms.CharField(min_length=4, widget=widgets.PasswordInput(attrs={"placeholder": "密码1", "class": "form-control"}))
    password2 = forms.CharField(min_length=4, widget=widgets.PasswordInput(attrs={"placeholder": "密码2", "class": "form-control"}))
    email = forms.EmailField(max_length=50, widget=widgets.EmailInput(attrs={"placeholder": "邮箱", "class": "form-control"}))
    valid_code = forms.CharField(min_length=6, max_length=6, widget=widgets.TextInput(attrs={"placeholder": "验证码", "class": "form-control"}))

    def __init__(self, request, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.request = request

    # def clean_password1(self):
    #     if self.cleaned_data['password1'].isalpha() or self.cleaned_data['password1'].isdigit():
    #         raise ValidationError('密码不能全为数字或者字母')
    #
    #     else:
    #         return self.cleaned_data['password1']
    #
    # def clean_password2(self):
    #     if len(self.cleaned_data['password2']) < 6:
    #         raise ValidationError('密码长度小于六位')
    #     elif self.cleaned_data['password2'].isalpha() or self.cleaned_data['password2'].isdigit():
    #         raise ValidationError('密码不能全为数字或者字母')
    #     else:
    #         return self.cleaned_data['password2']
    #

    def clean_valid_code(self):
        if self.cleaned_data["valid_code"].upper() == self.request.session["valid_code"].upper():
            return self.cleaned_data["valid_code"]
        else:
            print('验证码错误')
            raise ValidationError("验证码错误！")

    def clean(self):
        if self.cleaned_data.get('password1','') == self.cleaned_data.get('password2',''):
            return self.cleaned_data
        else:
            raise ValidationError("密码不一致")

templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body > .comment_item{
            margin-top: 20px;
            background-color: #b9def0;
        }
         body > .comment_item > .comment-body{
            margin-left: 20px;
        }

        body > .comment_item > .comment-body > .comment_item > .comment-body{
            margin-left: 40px;
        }

    </style>

</head>
<body>

        <div class="comment_item">
            <div class="comment-header">2asdasd</div>
            <div class="comment-body">
                   <div class="comment_item">
                       <div class="comment-header">2你好</div>
                           <div class="comment-body">

                                <div class="comment_item">
                                   <div class="comment-header">2阿萨德</div>
                                   <div class="comment-body"></div>
                                 </div>

                           </div>
                   </div>

                   <div class="comment_item">
                       <div class="comment-header">2啊实打实</div>
                       <div class="comment-body"></div>
                   </div>

               </div>

        </div>

           <div class="comment_item">
               <div class="comment-header">2啊实打实</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2asdasd</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2你好</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2阿萨德</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2啊实打实</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2真的假的</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2写的很好</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2asdasd</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2你好</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2阿萨德</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2啊实打实</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2啊实打实</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2asdasd</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2你好</div>
               <div class="comment-body">
           <div class="comment_item">
               <div class="comment-header">2阿萨德</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2啊实打实</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2真的假的</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">3确实如此</div>
               <div class="comment-body"></div>
           </div>
       </div>
           </div>

           <div class="comment_item">
               <div class="comment-header">3顶一个</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2不错</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">3的深V就能看见谁像你</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">1asdasd</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2a阿萨德</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2阿萨德sadas</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2阿萨德sadas</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2阿斯达四大</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">2阿斯达四大啊实打实大声道按时的</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">1撒大声地阿萨德阿萨德阿萨德按时打算打手电阿萨德按时的按时打算的阿萨德按时打算的阿萨德按时的</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">1阿斯达四大</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">1秋风的夙愿</div>
               <div class="comment-body"></div>
           </div>

           <div class="comment_item">
               <div class="comment-header">1小三</div>
               <div class="comment-body"></div>
           </div>


</body>
</html>

templates/form_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>formData测试</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/login.css">
        <script src="/static/js/jquery-3.2.1.js"></script>
</head>
<body>
    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <form id="post_form">
                  <div class="form-group">
                    <label for="username">username</label>
                    <input type="email" class="form-control" id="username" placeholder="用户名">
                  </div>

                  <div class="form-group">
                    <label for="pwd">Password</label>
                    <input type="password" class="form-control" id="pwd" placeholder="密码">
                  </div>

                  <div class="form-group">
                    <label for="upload_file">File input</label>
                    <input type="file" id="upload_file">
                    <p class="help-block">文件不能大于10M</p>
                  </div>

                  <input type="button" class="btn btn-success" id="submit_btn" value="提交">
                    {% csrf_token %}
                </form>

            </div>

        </div>
    </div>

</body>
<script>


    $('#submit_btn').click(function () {
        var $form_data = new FormData();
        $form_data.append("file", $("#upload_file")[0].files[0]);
        $form_data.append("username", $("#username").val());
        $form_data.append("file", $('#pwd').val());
        $form_data.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        $.ajax({
            url: '/test/',
            type:"POST",
            data: $form_data,
            processData: false,
            contentType: false,
            success: function(data){
                console.log(data)
            }
        })
    });


</script>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>

</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                  data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="{% url 'index' %}">博客园</a>

        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav">
                    <li class="active"><a href="#">link <span class="sr-only">(current)</span></a></li>

                    <li><a href="#">新闻</a></li>
                    <li><a href="#">小组</a></li>
                    <li><a href="#">收藏</a></li>
                    <li><a href="#">招聘</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                         aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                      </ul>
                    </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                  {% if request.user.is_authenticated %}
                    <li><a href="/blog/{{ request.user.username }}/">{{ request.user }}</a></li>
                    <li><a href="{% url 'logout' %}">退出登录</a></li>
                  {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                    <li><a href="">设置</a></li>
                  {% endif %}
              </ul>

        </div>

      </div>
    </nav>

    <div class="container-fluid">
        <div class="row">

            {# 左侧菜单 #}
            <div class="col-md-2 left_menu">

                <div class="left_menu_top_title">文章分类</div>

                {% for site_c in site_cates %}
                 <ul class="list-group">
                        <li class="left_menu_second_title">{{ site_c.title }}</li>

                        {% for detail in site_c.sitecatedetail_set.all %}
                          <li class="list-group-item hide">
                          {# 文章分类子类 #}
                              <a href="?cate={{ detail }}">{{ detail }}</a>
                          </li>
                         {% endfor %}

                </ul>
                {% endfor %}
            </div>

            {# 内容区 #}
            <div class="col-md-7">
                <div class="article_list">

                    {% for article in all_articles %}

                    <div class="article_item">
                        <h4 class="post_item_title"><a href="/blog/p/{{ article.nid }}/">{{ article.title }}</a></h4>
                        <div class="row post_item_body">

                             <div class="col-md-1">+96
{#                                 <img src="/media/{{ article.blog.user.avatar }}/" width="50px" height="50px">#}
                                 <img src="/media/{{ article.blog.user.avatar }}" width="50px" height="50px">
                             </div>

                            <div class="col-md-11 desc">
                                <p><a href="#">{{ article.desc }}</a></p>
                            </div>

                        </div>
                        <div class="post_item_foot">
                            <a href="/blog/{{ article.blog.site }}/">{{ article.blog.user.username }}</a>&nbsp;&nbsp;
                            <span class="item_create_time">发布于{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment" aria-hidden="true">评论({{ article.comment_num }})
                            </span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-eye-open">阅读({{ article.read_num }})</span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.poll_num }})</span>&nbsp;&nbsp;
                        </div>

                    </div>
                        <hr>
                    {% endfor %}

                </div>

            </div>

            {# 右侧菜单 #}
            <div class="col-md-3">

                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                  </div>
                  <div class="panel-body">1111</div>
                </div>

                <div class="panel panel-success">
                  <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                  </div>
                  <div class="panel-body">2222</div>
                </div>


            </div>
        </div>
    </div>

</body>
<script src="{% static 'js/login.js' %}"></script>
 <link rel="stylesheet" href="{% static 'css/login.css' %}">
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/login.css">
        <script src="/static/js/jquery-3.2.1.js"></script>
    <style>
        .register_post_form{
            margin-top: 100px;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-5">

                    <form class="register_post_form" enctype="multipart/form-data">
                        {% csrf_token %}
                          <div class="form-group">
                            <label for="username">用户名</label>
                              {{ register_form.username }}<span class="reg_error" id="username_err">
                          </span>
                          </div>

                          <div class="form-group">
                            <label for="password1">密码</label>
                              {{ register_form.password1 }}
                          </div>

                        <div class="form-group">
                            <label for="password2">确认密码</label>
                            {{ register_form.password2 }}<span class="reg_error" id="password2_err"></span>
                          </div>

                        <div class="form-group">
                            <label for="email">邮箱</label>
                            {{ register_form.email }}<span class="reg_error" id="email_err"></span>
                          </div>

                         <div class="form-group avatar">
                            <label for="image">头像</label>
                            <img src="{% static 'img/fang.jpg' %}" alt="" id="image" class="av">
                             <input type="file" id="file_choose" class="av">
                             <span class="reg_error" id="file_error"></span>
                          </div>

                        <div class="form-group valid_code">
                            <label for="valid_code">验证码</label>
                            <div class="row">
                                <div class="col-md-6">
                                    {{ register_form.valid_code }}<span class="reg_error" id="valid_code_err"></span>
                                </div>

                                <div class="col-md-6">
                                    <img src="/captcha/" width="213" height="35" class="valid_img"><a class="refersh">刷新</a>
                                </div>
                            </div>
                          </div>

                        <p class="error company-tips" id="error_tips"></p>

                        <input type="button" value="提交" id="submit_btn" class="btn btn-success">

                        <input type="reset" style="display: none" id="reset_btn">

                    </form>

                </div>
        </div>
    </div>

</body>
    <script src="/static/js/login.js"></script>
    <script>

        $('#file_choose').change(function () {
            // 1. 找到已更换的图片路径
            var reader = new FileReader();

            // 2. 从input标签中找到上传的文件对象, [0]是找到DOM对象
            var upload_file = $(this)[0].files[0];

            // 3. 处理上传的图片路径
            upload_file_url = reader.readAsDataURL(upload_file);

            // 4. 给reader对象绑定load事件
            reader.onload=function () {
                // 5. 修改img的src路径
                $('#image')[0].src = this.result  // 取出result对象,里面包含图路径

            }});


        // 图片放大显示
        $('#file_choose').mouseover(function () {
            $('#image').addClass("big_pic")

        });

        // 移开则缩小图片
        $('#file_choose').mouseleave(function () {
            $('#image').removeClass("big_pic")

        });

        // 点击提交按钮
        $('#submit_btn').click(function () {
            alert(1)
            // 实例化formdata对象
            var form_data = new FormData();

            // 填充数据
            form_data.append('username', $('#id_username').val());
            form_data.append('password1', $('#id_password1').val());
            form_data.append('password2', $('#id_password2').val());
            form_data.append('file_choose', $('#file_choose')[0].files[0]);
            form_data.append('valid_code', $('#id_valid_code').val());
            form_data.append('email', $('#id_email').val());
            form_data.append('csrfmiddlewaretoken', $('[name="csrfmiddlewaretoken"]').val());

            if(typeof ($('#file_choose')[0].files[0]) == 'undefined'){
                alert('请上传文件');
                return
            }

            var file_type = $('#file_choose')[0].files[0].type;
            if (file_type != 'image/png' && file_type != 'image/jpg' && file_type != 'image/gif' &&
                file_type != 'image/jpeg'){
                alert('上传的不为图片类型');
                return
            }

            if($('#file_choose')[0].files[0].size>1048576){
                alert('上传文件过大');
                return
            }

            $.ajax({
                url: '/register/',
                type: 'post',
                data: form_data,
                processData:false,   // formData使用必带内容
                contentType:false ,
                success: function (data) {
                    if (data.status=='success'){
                        window.location='/login/'

                    }
                    else if(data.status == 'fail'){
                        console.log(data.form_error);
                        var err_dict = data.form_error;
                        console.log(err_dict.__all__[0]);
                        for(i in err_dict){

                            $('#'+i+'_err').text(err_dict[i][0])
                        }
                        if (err_dict.__all__){
                            $('#password2_err').text(err_dict.__all__[0])}
                    }
            }
            })
        })
    </script>

</html>